# Generated by Django 5.2.3 on 2025-06-19 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('sepsis_risk', 'Sepsis Risk'), ('high_lactate', 'High Lactate'), ('hypotension', 'Hypotension'), ('tachycardia', 'Tachycardia')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('explanation', models.JSONField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patient')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='alerts_aler_patient_7b54c1_idx')],
            },
        ),
    ]
