version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: sepsis_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:7
    restart: always
    container_name: redis
    ports:
      - "6379:6379"

  django:
    build: .
    container_name: django
    command: >
      sh -c "./wait-for-it.sh db:3306 -- 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - qdrant
      - redis
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: sepsis_db
      DJANGO_DB_USER: user
      DJANGO_DB_PASSWORD: password

  worker:
    build: .
    container_name: celery_worker
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - qdrant
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: sepsis_db
      DJANGO_DB_USER: user
      DJANGO_DB_PASSWORD: password

volumes:
  db_data:
  qdrant_data:
