version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: sepsis_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  django:
    build: .
    container_name: django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - qdrant
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: sepsis_db
      DJANGO_DB_USER: user
      DJANGO_DB_PASSWORD: password
    command: >
      sh -c "./wait-for-it.sh db:3306 -- 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  db_data:
  qdrant_data:
