# Generated by Django 5.2.3 on 2025-07-04 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocols', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, help_text='Optional link to protocol document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='protocols.knowledgedocument')),
            ],
        ),
        migrations.CreateModel(
            name='TagCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('tag', 'Tag'), ('field', 'Field'), ('event', 'Event')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('field_path', models.CharField(blank=True, max_length=255, null=True)),
                ('operator', models.CharField(blank=True, choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<='), ('==', '=='), ('!=', '!=')], max_length=10, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('time_relation', models.CharField(blank=True, choices=[('before', 'Before'), ('after', 'After'), ('any', 'Any')], max_length=10, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='agent.tag')),
            ],
        ),
    ]
