# Generated by Django 5.2.4 on 2025-07-08 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agentexecutionlog_agentexecutionevent'),
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagcondition',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tagcondition',
            name='time_relation',
        ),
        migrations.AddField(
            model_name='tagcondition',
            name='expression',
            field=models.TextField(blank=True, help_text='Free-text expression for complex or non-structured logic', null=True),
        ),
        migrations.AlterField(
            model_name='tagcondition',
            name='condition_type',
            field=models.CharField(choices=[('tag', 'Tag'), ('field', 'Field'), ('event', 'Event'), ('natural_language', 'Natural Language')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tagcondition',
            name='operator',
            field=models.CharField(blank=True, choices=[('<', '<'), ('>', '>'), ('<=', '<='), ('>=', '>='), ('==', '=='), ('!=', '!=')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='protocols.knowledgedocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='chunk',
            field=models.ForeignKey(blank=True, help_text='Chunk do qual essa tag foi extraída', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.documentchunk'),
        ),
    ]
