# Generated by Django 5.2.3 on 2025-06-20 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antibiogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CultureResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=20)),
                ('reported_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('collected_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AntibioticSusceptibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antibiotic', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('S', 'Susceptible'), ('I', 'Intermediate'), ('R', 'Resistant')], max_length=20)),
                ('antibiogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='susceptibilities', to='sepsis.antibiogram')),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('culture_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisms', to='sepsis.cultureresult')),
            ],
        ),
        migrations.AddField(
            model_name='antibiogram',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antibiograms', to='sepsis.organism'),
        ),
        migrations.AddField(
            model_name='cultureresult',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_results', to='sepsis.sample'),
        ),
        migrations.CreateModel(
            name='SepsisEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sepsis_episodes', to='patients.patient')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='sepsis.sepsisepisode'),
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(max_length=50)),
                ('exam_name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('observed_at', models.DateTimeField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='sepsis.sepsisepisode')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='sepsis.sepsisepisode')),
            ],
        ),
        migrations.CreateModel(
            name='AntibioticAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField()),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('dose', models.CharField(blank=True, max_length=100, null=True)),
                ('route', models.CharField(blank=True, max_length=50, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antibiotics', to='sepsis.sepsisepisode')),
            ],
        ),
        migrations.CreateModel(
            name='VitalsObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('blood_pressure_sys', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_dia', models.IntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='sepsis.sepsisepisode')),
            ],
        ),
    ]
