# Generated by Django 5.2.3 on 2025-07-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('infection_protocol', 'Infection Protocol'), ('institutional_protocol', 'Institutional Protocol'), ('governmental_protocol', 'Governmental Protocol'), ('flowchart', 'Flowchart'), ('other', 'Other')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('minio_path', models.CharField(max_length=255, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
