# Generated by Django 5.2.3 on 2025-06-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField(default=True)),
                ('records_ingested', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
