# Generated by Django 5.2.3 on 2025-06-19 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(max_length=50)),
                ('exam_name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='final', max_length=50)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='patients.patient')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['patient', 'exam_code', 'observed_at'], name='labs_labres_patient_6ed034_idx')],
            },
        ),
    ]
