# Generated by Django 5.2.3 on 2025-06-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labresult',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='labresult',
            name='labs_labres_patient_6ed034_idx',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='reference_range',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='status',
        ),
        migrations.AddField(
            model_name='labresult',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
